save_dir: /data/localhost/not-backed-up/nvme00/spoendli/Graphlexibility/data/EGNN_training_outputs/
name: '1'
log: True
restore: False
test: True
test_CDR: True

logger_params: # logging with wandb
  entity: f-spoendlin
  group:  cutoff_2A_new
  log_interval: 10
  print_interval: 50
  project: graphlexibility_align_loops

model: flexEGNN
model_params:
  num_node_features: 22 #22 #27 # 1 + 21 + 5
  lr: 2.e-4
  weight_decay: 1.e-6
  dropout: 0.2
  num_edge_features: 9
  egnn_layer_hidden_nfs: [128,128,128]
  embedding_in_nf: 128
  embedding_out_nf: 128
  num_classes: 1    
  attention: False
  residual: True
  normalize: False
  tanh: True
  update_coords: True
  scheduler: CosineAnnealing
  norm_nodes: None
  reload_best_model: False
  encode_length: False # True

trainer_params:
  accumulate_grad_batches: 1
  max_epochs: 100
  # accelerator: 'auto'
  num_nodes: 1
  gradient_clip_val: 10

loader_params:
  batch_size: 32
  num_workers: 4
  balanced_sampling: False

dataset_params:
  cache_frames: False
  force_recalc: False                # recalculate parquet files
  graph_mode: loop_context
  interaction_dist: 10
  context_inclusion_dist: 10
  typing_mode: ['res_type'] #['res_type', 'atom_type'], ['res_type']
  edge_encoding: ['covalent', 'rbf']
  residues_to_encode: ['CA'] #['N', 'CA', 'C', 'O'] #['CA']
  aa_map_mode: 'extended'
  length_scale:
    mean: 6.7
    std: 3.9
  input_files:
    train:
      - /vols/opig/users/spoendli/data/pdb_loop_datasets/train_no_overlap_mAbs_TCRs_v2_cutoff_2_EGNN_5_strucs_per_seq.csv
    val:
      - /vols/opig/users/spoendli/data/pdb_loop_datasets/val_no_overlap_mAbs_TCRs_v2_cutoff_2_EGNN_5_strucs_per_seq.csv
    test:
      - /vols/opig/users/spoendli/data/pdb_loop_datasets/test_cutoff_2_EGNN.csv
    test_CDRH3:
      - /vols/opig/users/spoendli/data/CDRH3_datasets/5_pdbs/CDRH3_Fv_all_EGNN_dssp_both_chains_cutoff_2.csv
    test_CDRL3:
      - /vols/opig/users/spoendli/data/CDRH3_datasets/5_pdbs/CDRL3_Fv_all_EGNN_dssp_both_chains_cutoff_2.csv
    test_CDRB3:
      - /vols/opig/users/spoendli/data/CDRH3_datasets/5_pdbs/CDRB3_Fv_all_EGNN_dssp_both_chains_cutoff_2.csv
    test_CDRA3:
      - /vols/opig/users/spoendli/data/CDRH3_datasets/5_pdbs/CDRA3_Fv_all_EGNN_dssp_both_chains_cutoff_2.csv