save_dir: ../data/training/
name: 'initial'
log: False
restore: False
test: True

logger_params: # logging with wandb
  entity: username
  group:  group_name
  log_interval: 10
  print_interval: 50
  project: project_name

model: flexEGNN
model_params:
  num_node_features: 22
  lr: 2.e-4
  weight_decay: 1.e-6
  dropout: 0.2
  num_edge_features: 9
  egnn_layer_hidden_nfs: [128,128,128]
  embedding_in_nf: 128
  embedding_out_nf: 128
  num_classes: 1    
  attention: False
  residual: True
  normalize: False
  tanh: True
  update_coords: True
  scheduler: CosineAnnealing
  norm_nodes: None
  reload_best_model: False

trainer_params:
  accumulate_grad_batches: 1
  max_epochs: 200
  accelerator: 'auto'
  num_nodes: 1
  gradient_clip_val: 10

loader_params:
  batch_size: 32
  num_workers: 4
  balanced_sampling: False

dataset_params:
  cache_frames: False
  graph_mode: loop_context
  interaction_dist: 20
  context_inclusion_dist: 30
  typing_mode: res_type
  edge_encoding: ['covalent', 'rbf']
  aa_map_mode: 'extended'
  input_files:
    train:
      - ../data/train_align_anchors.csv
    val:
      - ../data/val_align_anchors.csv
    test:
      - ../data/test_align_anchors.csv
