save_dir: /data/localhost/not-backed-up/nvme00/spoendli/Graphlexibility/data/EGNN_training_outputs/
name: '1'
log: True
restore: False
test: True
test_CDR: True

logger_params: # logging with wandb
  entity: username
  group:  group_name
  log_interval: 10
  print_interval: 50
  project: project_name

model: flexEGNN
model_params:
  num_node_features: 22 #22 #27 # 1 + 21 + 5
  lr: 2.e-4
  weight_decay: 1.e-6
  dropout: 0.2
  num_edge_features: 9
  egnn_layer_hidden_nfs: [128,128,128]
  embedding_in_nf: 128
  embedding_out_nf: 128
  num_classes: 1    
  attention: False
  residual: True
  normalize: False
  tanh: True
  update_coords: True
  scheduler: CosineAnnealing
  norm_nodes: None
  reload_best_model: False
  encode_length: False

trainer_params:
  accumulate_grad_batches: 1
  max_epochs: 100
  # accelerator: 'auto'
  num_nodes: 1
  gradient_clip_val: 10

loader_params:
  batch_size: 32
  num_workers: 4
  balanced_sampling: False

dataset_params:
  cache_frames: False
  force_recalc: False                # recalculate parquet files
  graph_mode: loop_context
  interaction_dist: 10
  context_inclusion_dist: 10
  typing_mode: ['res_type'] #['res_type', 'atom_type'], ['res_type']
  edge_encoding: ['covalent', 'rbf']
  residues_to_encode: ['CA'] #['N', 'CA', 'C', 'O']
  aa_map_mode: 'extended'
  length_scale:
    mean: 6.7
    std: 3.9
  input_files:
    train:
      - ../data/train_align_loops.csv
    val:
      - ../data/val_align_loops.csv
    test:
      - ../data/test_align_loops.csv
    test_CDRH3:
      - ../data/CDRH3_test_align_loop.csv
    test_CDRL3:
      - ../data/CDRL3_test_align_loop.csv
    test_CDRB3:
      - ../data/CDRB3_test_align_loop.csv
    test_CDRA3:
      - ../data/CDRA3_test_align_loop.csv