#!/bin/bash
#SBATCH -J ITsFlexible_train # Job name
#SBATCH --time=14-00:00:00 # Walltime
#SBATCH --cluster swan
#SBATCH --cpus-per-task=4
#SBATCH --mem=20G # total memory (in MB)
#SBATCH --gres=gpu:Quadro_RTX_6000:1
#SBATCH --ntasks-per-node=1 # 1 tasks
#SBATCH --nodes=1 # number of nodes
#SBATCH --partition=high-opig-gpu # Select a specific partition rather than default
#SBATCH -w nagagpu03.cpu.stats.ox.ac.uk # Provide a specific node/nodelist rather than the standard nodelist associated with the parti    tion (useful if you have a data setup on one specific node)
#SBATCH --output=/vols/opig/users/spoendli/ITsFlexible/slurms/slurm_%j.out # Writes standard output to this file. %j is     jobnumber
#SBATCH --error=/vols/opig/users/spoendli/ITsFlexible/slurms/slurm_%j.out # Writes error messages to this file. %j is j    obnumber

bash
source /data/localhost/not-backed-up/spoendli/miniconda3/bin/activate

cd /data/localhost/not-backed-up/nvme00/spoendli/

echo "Copy repo"
rsync -av /vols/opig/users/spoendli/ITsFlexible .

# echo "extract data"
# tar -xzvf /data/nagagpu03/not-backed-up/nvme00/spoendli/pdb_files_112023.tar.gz

# echo "Install env"
# conda create -n ITsFlexible_env python=3.10
conda activate ITsFlexible_env

# pip install torch

cd ITsFlexible
git switch backbone_enc
pip install .

# pip install torch_geometric
# pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.7.0+cu126.html

# conda install -c conda-forge openbabel
# conda install -c anaconda pyyaml
conda deactivate

echo "start training"
conda activate ITsFlexible_env
cd /data/localhost/not-backed-up/nvme00/spoendli/ITsFlexible/scripts
# python train_val_test_CDR.py --accelerator gpu
python train_val_test_CDR_n.py --accelerator gpu --n 10 --predictor loop